### ISSUE TITLE
BUG: no user data is being sent by dj-rest-auth

### ISSUE THREAD

**Issue by Parbelaez** [Parbelaez/front_end_pp5_positive#9]
When trying to get the username from the user by using dj-rest-auth/user/ a 403 bad request message is being received:

{
"message": "Request failed with status code 403",
"name": "AxiosError",
"stack": "AxiosError: Request failed with status code 403\n at settle ([https://3000-parbelaez-frontendpp5po-eny30k5q3az.ws-eu106.gitpod.io/static/js/bundle.js:61662:12)\n](https://3000-parbelaez-frontendpp5po-eny30k5q3az.ws-eu106.gitpod.io/static/js/bundle.js:61662:12)/n) at XMLHttpRequest.onloadend (https://3000-parbelaez-frontendpp5po-eny30k5q3az.ws-eu106.gitpod.io/static/js/bundle.js:60344:66)",
"config": {
"transitional": {
"silentJSONParsing": true,
"forcedJSONParsing": true,
"clarifyTimeoutError": false
},
"adapter": [
"xhr",
"http"
],
"transformRequest": [
null
],
"transformResponse": [
null
],
"timeout": 0,
"xsrfCookieName": "XSRF-TOKEN",
"xsrfHeaderName": "X-XSRF-TOKEN",
"maxContentLength": -1,
"maxBodyLength": -1,
"env": {},
"headers": {
"Accept": "application/json, text/plain, */*"
},
"baseURL": "https://positive-api-55b6b5b25a88.herokuapp.com/",
"withCredentials": true,
"method": "get",
"url": "dj-rest-auth/user/"
},
"code": "ERR_BAD_REQUEST",
"status": 403
}

**Comment by Parbelaez** [comment]
There is a problem with auth==0.55.0 that is not compatible with dj-rest-auth.
The version was needed to be changed to a lower compatible one
